#!/bin/bash

declare -A filecksums

falseFiles=$(grep "^false" ./record/* -Irn | cut -d':' -f1 | cut -d'/' -f1-3)
#echo $falseFiles
#files=$(find ./record -name "schedExec" -print)
schedExecFiles=
for fi in $falseFiles
do
    if [[ -e "$fi/schedExec" ]]
    then
	if [ "$schedExecFiles" == "" ];then
	    schedExecFiles="$fi/schedExec"
	else
	    schedExecFiles="$schedExecFiles $fi/schedExec"
	fi
    fi
done
if [[ ! -e "./progSched" ]]
then
    touch ./progSched
fi
schedExecFiles="$schedExecFiles ./progSched"
echo $schedExecFiles

# No args, use files in current directory
test 0 -eq $# && set -- *

counter=0
#for file in "$@"
for file in $schedExecFiles
do
    # Files only (also no symlinks)
    [[ -f "$file" ]] && [[ ! -h "$file" ]] || continue

    # Generate the checksum
    cksum=$(cksum <"$file" | tr ' ' _)

    # Have we already got this one?
    if [[ -n "${filecksums[$cksum]}" ]] && [[ "${filecksums[$cksum]}" != "$file" ]]
    then
	((counter++))
        echo "Found '$file' is a duplicate of '${filecksums[$cksum]}'" >&2
    else
        filecksums[$cksum]="$file"
    fi
done
echo "finding for duplication is done"
echo "found $counter many duplication" 
